#SkillPractice: Average Grade, Elisheva kibbie


g1 = float(input("grade for 1st period:"))
g2 = float(input("grade for 2ed period:"))
g3 = float(input("grade for 3rd period:"))
g4 = float(input("grade for 4th period:"))
g5 = float(input("grade for 5th period:"))
g6 = float(input("grade for 6th period:"))
g7 = float(input("grade for 7th period:"))
g8 = float(input("grade for 8th period:"))

gpa = (g1+g2+g3+g4+g5+g6+g7+g8)/8

print("your avrage score:", gpa)
